Produtos
Felipe041198/ClothingStore pull request #11
Opened 2024-11-01 13:08 UTC by iris-souza

2024-11-01 19:25 UTC, Felipe041198 requested changes

2024-11-01 19:25 UTC, Felipe041198 commented on src/controller/controlador_clientes.py
> +    def cadastrar_cliente(self):
Por que você parou de retornar o cliente?
```suggestion
    def cadastrar_cliente(self -> Cliente):
```

2024-11-01 19:25 UTC, Felipe041198 commented on src/controller/controlador_clientes.py
> +        cliente_existente = self.busca_cliente(cliente.cpf)
Não gostei dessa abordagem, o melhor seria avisar o cara que o CPF quando ele digitar o CPF e não depois de preencher todos os dados. Mas acho melhor fazer isso depois.

2024-11-01 19:25 UTC, Felipe041198 commented on src/controller/controlador_clientes.py
> +        self.__tela_clientes.exibir_cliente(cliente)
Não precisa mostrar o cliente, o cara acabou de digitar os dados, se rolar o terminal pra cima da pra ver

2024-11-01 19:25 UTC, Felipe041198 commented on src/view/abstract_tela_cadastro.py
> +class AbstractTelaCadastro(AbstractTela, ABC):
```suggestion
class AbstractTelaCadastro(AbstractTela):
```

Esse ABC é realmente necessário?

2024-11-01 19:25 UTC, Felipe041198 commented on src/view/tela_clientes.py
> +from titi.ClothingStore.src.utils.validador import Validador
Acho que esse import ta errado
```suggestion
from src.utils.validador import Validador
```

2024-11-01 19:25 UTC, Felipe041198 commented on src/view/tela_vendedores.py
> +from titi.ClothingStore.src.utils.validador import Validador
```suggestion
from src.utils.validador import Validador
```

2024-11-01 22:24 UTC, iris-souza commented on src/controller/controlador_clientes.py
> +        cliente_existente = self.busca_cliente(cliente.cpf)
ah sim, posso arrumar depois

2024-11-01 22:25 UTC, iris-souza commented on src/controller/controlador_clientes.py
> +        self.__tela_clientes.exibir_cliente(cliente)
era pra eu ver se tinha passado tudo certo, dava none

2024-11-02 01:15 UTC, Felipe041198 approved these changes

2024-11-02 01:16 UTC, merged

2024-11-02 02:00 UTC, iris-souza commented on src/controller/controlador_clientes.py
> +        if cpf is None:
quando tu seleciona buscar no menu chama essa função, como tu não tem um cpf vai pedir qual o cpf que tu quer pesquisar. mas essa função de busca é usada por outras funções, ja recebendo um pdf pelo outra função, então não pede na tela.